### ISSUE TITLE
球速那么快，怎么跟踪？

### ISSUE THREAD

**Issue by Ocxs** [Mooophy/balls_tracker#2]
话说你是cv是你读phD or master的方向？

**Comment by Mooophy** [comment]
不是啊。
我大四在读，就接触点儿皮毛，而且对CV无爱。完全是应付了事。

**Comment by Ocxs** [comment]
@Mooophy 额，你咋还大四在读啊，我3月份问C++的时候你说你大四，现在我都大四了，你还大四，难道学制不一样，还是我之前弄错了，你之前是大三？

**Comment by Mooophy** [comment]
我又多选了两门课。。没急着毕业

**Comment by Ocxs** [comment]
soga :smile:
